### ISSUE TITLE
There is an error in the function: getNNOrder

### ISSUE THREAD

**Issue by PhoebeTsou** [blackball/SquaredCirclePattern#1]
In squaredcirclepattern.cpp, line 386, 507

The grid size is a hard code.

**Comment by blackball** [comment]
@PhoebeTsou Thank you for your careful code review. I will change the hard coded codes as soon as I am convenient. Or you could file a pull request, it will be appreciated. ;-)

**Comment by PhoebeTsou** [comment]
The code is updated. You can check it.

**Comment by blackball** [comment]
@PhoebeTsou Great! Have you tested it ? If so, you can sent a pull request in your forked branch, then I will merge your contribution. Thanks!
